name: publish

on:
  push:
    branches:
      - "master"

jobs:
  publish-docker-example-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: print github.actor
        run: |
        echo "${{ github.actor }}"


      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.EXAMPLE_DOCKER_GITACTION}}

      - name: Build the example-docker-gitaction Docker image
        run: |
          docker build . --tag ghcr.io/lidongw90/docker-react/docker-gitaction-example:latest
          docker run ghcr.io/lidongw90/docker-react/docker-gitaction-example:latest
          docker push ghcr.io/lidongw90/docker-react/docker-gitaction-example:latest
