name: publish

on:
  push:
    branches:
      - "master"

jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.EXAMPLE_DOCKER_GITACTION}}

      - name: Build the example-docker-gitaction Docker image
        run: |
          docker build . --tag ghcr.io/Lidongwang-L/example-docker-gitaction:latest
          docker run ghcr.io/Lidongwang-L/example-docker-gitaction:latest
          docker push ghcr.io/Lidongwang-L/example-docker-gitaction:latest
